[tool.poetry]
name = "flugfeld"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
numpy = "^1.20.2"
geojson = "^2.5.0"
numba = "^0.53.1"
timezonefinder = {version = "^5.2.0", extras = ["numba"]}
scipy = "^1.6.2"
pytest = "^6.2.3"
Shapely = "^1.7.1"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
